### ISSUE TITLE
Html special characters are showing in the run descriptions

### ISSUE THREAD

**Issue by Gregliest** [AmericanWhitewater/aw-ios#100]
I'm seeing characters like `&nbsp;` and `&#39;`. I remember this being a real pain.

**Comment by riversandcreeks** [comment]
Yeah; I think we have stripped some of this but I have always been a fan of plain text for river descriptions. We have volunteers who love HTML tags and have overused to an extent that it creates problems across devices and platforms.

**Comment by duffek** [comment]
went ahead and added some checks to make sure this doesn't show up. I'm stripping all tags for display on this and decoding the string as well + manually checking for specific characters. Fix listed in TestFlight build 4.
