### ISSUE TITLE
Selecting multiple states not working

### ISSUE THREAD

**Issue by RacIVRnr** [AmericanWhitewater/aw-ios#104]
The app *seems* to allow selecting multiple states ("Regions"), showing the ones I've selected in a list at the top of that selection page. However, when I click "Done" to return to the river listing or the map page, I only see rivers in one of the states.

**Comment by duffek** [comment]
The map issues like this should be fixed in the next build version. Thanks!

**Comment by duffek** [comment]
Fixed on TestFlight Build 11
