### ISSUE TITLE
Filter page 'paging' is screwy

### ISSUE THREAD

**Issue by RacIVRnr** [AmericanWhitewater/aw-ios#105]
When I click the icon to go to the various 'Filter' options, the "USA Regions" page (to select which state(s) I want to see displayed) appears fine.

When I swipe or click the selector box at top of page to see the other filters (by class, or by distance), those pages do not center or lock-in onto the screen (at least, on my admittedly ancient Iphone 5s with IOS 12.4.2), but tend to come up a bit offset on the screen. This makes it impossible to see the class ratings AND the selection buttons at the same time! 

When I click or swipe to see the 'by distance' page, it's a little better, but still tends to be a bit 'off', showing the toggle switches for the "by class" filter, until I drag the screen a bit more to center this page.

**Comment by duffek** [comment]
Can you post a screen shot? This should be paging and you should have an option at the top of the screen to select each of these filters OR swipe to the next one.

**Comment by duffek** [comment]
Fixed in TestFlight Build 5 (release will be Thursday)
