### ISSUE TITLE
On first load, no runs showed up for a long time

### ISSUE THREAD

**Issue by Gregliest** [AmericanWhitewater/aw-ios#108]
On my first open after dl'ing the new Test Flight, the app landed on the runs list but showed no runs for 10-15s. There was also no spinner. I believe the app was loading, and we should have the spinner showing at that time, but it may be another issue.

**Comment by duffek** [comment]
Ya, this wasn't being set to refresh, just fixed it in upcoming build 12 that I just uploaded! Thanks!
