### ISSUE TITLE
Run details: clicking on gage does nothing

### ISSUE THREAD

**Issue by Gregliest** [AmericanWhitewater/aw-ios#109]
On the run details page, I believe that clicking on the top cell with the current gage reading used to take you to the gage detail page.

**Comment by duffek** [comment]
@Gregliest I never knew that is how it worked. I like that and will look at bringing that back into the app after we get a stable version out. I was going to update the *See Gauge Info* to do that instead. Right now it just shows the Gauge name and chart.

**Comment by Gregliest** [comment]
This is not relevant anymore with the "View and Report Flows" button right beneath this cell.
