### ISSUE TITLE
[Minor] Run Map: Excess zooming when clicking on the my location button

### ISSUE THREAD

**Issue by Gregliest** [AmericanWhitewater/aw-ios#111]
On the Clackamas river page, when I go to the map, it zooms on the pins as it should. When I click on the 'my location' button, even though I'm just off the frame of the map, the map scrolls for at least a second (looks like a pan and zoom out). It has not loaded any of the intervening maps, which makes for a jarring experience looking at unloaded map grids. I'm on wifi. This may have something to do with the default zoom level when scrolling to 'my location', but I haven't seen this behavior before.

**Comment by duffek** [comment]
Fixed, calculating region based on user location and annotations correctly now. TestFlight Build 20
