### ISSUE TITLE
News: Links don't work

### ISSUE THREAD

**Issue by Gregliest** [AmericanWhitewater/aw-ios#113]
Clicking on a link in a news article does nothing. @duffek I believe this is an old issue, and relatively difficult to fix with the way scrolling text views work. Don't worry about it, unless you know of an easy fix.

**Comment by duffek** [comment]
@Gregliest do you know which news article you saw this in? Would like to look into it. Right now I'm stripping out all HTML tags which is probably the issue. But we can turn on attributed text and link detection to make it work.

**Comment by Gregliest** [comment]
The most recent two have links, "AW LAUNCHES HIWASSEE DRIES (TN/NC) FLOW SURVEY" and " HALLOWEEN VOTE IN THE HOUSE ON IMPORTANT PUBLIC LAND AND RIVERS PROTECTING BILLS"

**Comment by AWKevin** [comment]
If I click the link and hold my finger on it for a second it opens up option for opening the link. Not perfect, but this did work for me. I think this is a low priority to fix, but should remain on the list.

**Comment by Gregliest** [comment]
This seems to be working as Kevin said. I think that's the appropriate solution, because otherwise we'd have to open some sort of webview in the app.
