### ISSUE TITLE
Gage page missing most of the information

### ISSUE THREAD

**Issue by Gregliest** [AmericanWhitewater/aw-ios#114]
The gage page for the Clackamas river is only showing the gage title and the graph. 

Missing pieces are:
- [top bar] share button
- [top cell ] last updated time 
- [top cell] last reading
- [top cell] runnability level
- [bottom table] a table showing all of the runs that use this gage. 

![IMG_0506](https://user-images.githubusercontent.com/4493287/68040255-33ba1e80-fc8b-11e9-93b5-288224f8d942.PNG)

The designs and old version of the app look more like this: 
<img width="378" alt="Screen Shot 2019-11-01 at 9 37 45 AM" src="https://user-images.githubusercontent.com/4493287/68040299-4c2a3900-fc8b-11e9-98f6-60ce8bfcd3bb.png">
Two details in this design that I don't think were in the old version of the app.
- favorites button in top bar
- range buttons for the graph (5 days, 30 days, etc)

**Comment by duffek** [comment]
Hey thanks for posting that view. I always ran into issues seeing how this would be viewed due to some of the past issues. Will add this as soon as I can!

**Comment by AWKevin** [comment]
Did we used to have the runnable ranges listed somewhere, or color coded bars on the graphs like we do on the website? This is pretty critical info too.

**Comment by Gregliest** [comment]
Pretty sure we didn't, but I agree it should be there.

**Comment by AWKevin** [comment]
OK lets park my question as a future enhancement.

**Comment by AWKevin** [comment]
The screenshot above has the important color coding and gage read out on it. I think that is important to re-integrate.

**Comment by AWKevin** [comment]
While not part of the original app, the most important thing to me on this page would be to show the Runnable range(s). To me it matters what the range is, because 199 might be red, but 200 green, and if its 199 Im going boating. Is there an easy way to show the range?

**Comment by duffek** [comment]
I'm looking into this. I think this information is provided but I'm not sure if its in the old API or the new one. I'll find out and add it if we can. I also need to add a map icon and the favorite icon. 

@Gregliest can you explain what the bottom of the gage details represent. Is it supposed to be all the rivers that go with that gage? Or is it a list of gages that go with that Reach? And what does the map icon do?

**Comment by Gregliest** [comment]
The bottom list is all of the reaches that go with that gage. 

I agree with Kevin. If possible, we should replace the "runnability level" text with the runnable range. However I seem to remember that info isn't included in the api response, so it might be difficult. Might be worth opening a separate issue as an enhancement for that.

**Comment by duffek** [comment]
@AWKevin so we have this information on the main reach listing. I can add that info to this view as well for consistency. 
![image](https://user-images.githubusercontent.com/6788776/105198103-4ed0b280-5b0b-11eb-9484-debbfd984846.png)
You can see that in the image above. 

Right now, with the new API I'm not seeing a way to get the list of Reaches for a gage. I'll double check this with Ryan. For now, the listing below I have is all of the gages that are connected to the selected Reach. We can certainly change this over as soon as that comes available and I can check with ryan and add a feature request to the wh2o project.

**Comment by AWKevin** [comment]
The info that I was suggesting made sense is not pictured. The runnable range is what I was suggesting should be depicted within the app if possible. Here is is on the AW site, for South Mills River: 

![Screen Shot 2021-01-20 at 10 57 30 AM](https://user-images.githubusercontent.com/7936679/105201051-6e1d0f00-5b0e-11eb-8721-b113bd066f94.png)

**Comment by duffek** [comment]
@AWKevin thank you! I understand what you mean now. I can get that listed on the app as we clearly have that data. Let me check into it today and I'll know more. I may break up this issue into multiple issues based on what is completed and what is yet to be done if I need a little time on it.

**Comment by AWKevin** [comment]
It would be really nice if the gage listed on the "See Gage Info" page would be hyperlinked to the source gage. I think people want to double check the source gage. I know I do! Can we hyperlink the Gage name in the red circle below?

![IMG_5898](https://user-images.githubusercontent.com/7936679/126375427-6056453a-5d99-48d8-a5d9-8e622544c76f.jpg)

**Comment by Gregliest** [comment]
That would be great, can you make a separate ticket for that?

**Comment by Gregliest** [comment]
I'm going to close this issue and open a new one for runnability range. Looks like the share button and reaches for the gage aren't done, but I'm not sure that we need those anyway.
