### ISSUE TITLE
Title bar: Font and color

### ISSUE THREAD

**Issue by Gregliest** [AmericanWhitewater/aw-ios#115]
It looks like the font and color of the top bar is different on the run details and filter pages: 
![IMG_0509](https://user-images.githubusercontent.com/4493287/68040974-b8f20300-fc8c-11e9-8821-d1eed400898c.PNG)

- Unselected font should be white
- Selected should be blue.
- Font should be open sans, although it's more important to be consistent with the rest of the app.
- Check the font size as well, should be 13pt.

**Comment by duffek** [comment]
Great catch. Thanks!

**Comment by duffek** [comment]
This should now be fixed on all Segmented Controllers. TestFlight 18
