### ISSUE TITLE
Fonts changes?

### ISSUE THREAD

**Issue by Gregliest** [AmericanWhitewater/aw-ios#116]
Generally, it looks like there might be some inconsistency in the fonts throughout the app. I believe the old app was all in OpenSans, was this changed in some places?

**Comment by duffek** [comment]
Most likely not applied across the board. I have been trying to get the core functionality back up and running so we have a stable app out. Then can fix a lot of these tweaks while we add the needed new features. Thanks for pointing it out!

**Comment by duffek** [comment]
These are fixed and added in the correct font for the American Whitewater heading for on-boarding.  TestFlight 18
