### ISSUE TITLE
Several Map Filter Issues (V14)

### ISSUE THREAD

**Issue by AWKevin** [AmericanWhitewater/aw-ios#117]
The app is currently showing rivers within 100 miles of Asheville, NC (for me).

It opened to a map view of Salt Lake City, where I am at. When I refresh my location it still only shows the Asheville area rivers. When I go to Region and select Utah it still only shows Asheville area rivers.

**Comment by duffek** [comment]
With the map, it might be best to just do any around the current location within a distance & the regional ones instead of an OR. This would mean you would always see both.

**Comment by duffek** [comment]
Fixed in TestFlight 18
