### ISSUE TITLE
Filtering still confusing

### ISSUE THREAD

**Issue by AWKevin** [AmericanWhitewater/aw-ios#118]
The filtering is strange still:

- If I select distance and turn off region, I still see Utah rivers on my map and list plus local rivers. (I am back in NC). Even if I select a new region (which works), when I go back to distance Utah pops back into the mix. I can't make Utah go away. 

- When I select a distance (100 miles), and then try to zoom out to see it all on the map, the app zooms back in to a tighter zoom after a second or two. This is kind of crazy-making, and more importantly makes it nearly impossible to select rivers within the range but out of the view via the map. 

- When I select a region, I see all rivers in the US on the map, which is confusing IU/UX, though the list builds correctly.

**Comment by duffek** [comment]
Fixed in TestFlight Build 19
