### ISSUE TITLE
Clicking on the Arrow/Zoom-to-me Button Froze map

### ISSUE THREAD

**Issue by AWKevin** [AmericanWhitewater/aw-ios#120]
Not sure why, but this made the map very slow to update for moving or selecting icons.

**Comment by duffek** [comment]
Thanks, I think I see what's going on here.

**Comment by duffek** [comment]
Looks like a small bug was showing all rivers across the nation which can be pretty slow, especially when we update all the rivers. fixed in TestFlight Build 19
