### ISSUE TITLE
Change tab order on main page

### ISSUE THREAD

**Issue by Gregliest** [AmericanWhitewater/aw-ios#123]
So we had decided to move the "Runs" tab to be first. However, logically, "Runs" and "Map" go together (right now "Favorites" is in between). Another consideration is that we should land on "Favorites" if favorites are present and "Runs" if not. Given the above, I think probably the best ordering is:

Runs - Map - Favorites - News - More

Thoughts?

**Comment by duffek** [comment]
Works for me. I think it's better for the paddlers to see Favorites first BUT better for AW to show the News first. Forces people to see the first few issues/events/notices that AW has put out. On the main AW site I always want to go right to the River DB but tend to stop on the News section when I see something I normally would have skipped over. 

For now I'll change it to what you listed and if @AWKevin wants anything different we can change it again.

**Comment by duffek** [comment]
Sorry I'll leave this open until we hear back from @AWKevin or if he's on the call today I'll find out.

**Comment by AWKevin** [comment]
A agree with Greg, we can put the runs up front and have news follow. Close this one..
