### ISSUE TITLE
Run Details -> Map: back and share button aren't showing

### ISSUE THREAD

**Issue by Gregliest** [AmericanWhitewater/aw-ios#124]
On a run detail page, when on the "details" tab, there is a back arrow and share button in the title bar. However, when you go to the "map" tab, the back arrow and share button are hidden. They should show.

**Comment by duffek** [comment]
There is a  little bit of a hack going on here that I need to fix. It's showing a new view instead of having a subview. Thats why we get the ugly transition. I'll get this as soon as all the major issues are fixed. It's on my priority list.

**Comment by AWKevin** [comment]
There is also no back button after a search. Once you search for a river, you are kind of stuck with the results.

**Comment by duffek** [comment]
You can hit the X but adding something that is more clear will be important.

**Comment by AWKevin** [comment]
x clears the search box, but does not go back to the full state or regional list.

**Comment by AWKevin** [comment]
There is a back button on the map now, but not a share button. I think that is OK. Closing because this is sufficient functionality.
