### ISSUE TITLE
Filter page: Selected tab shows all white background

### ISSUE THREAD

**Issue by Gregliest** [AmericanWhitewater/aw-ios#125]
Selected tab text is not visible because the background and text is white. 

![IMG_0734](https://user-images.githubusercontent.com/4493287/69085082-532aa880-09fa-11ea-8f01-49787ab78553.PNG)

**Comment by duffek** [comment]
What device and build are you testing on? I'm not seeing this same behavior?

**Comment by duffek** [comment]
Never mind, I see it. Issue with iOS 13+ ... got it fixed.
