### ISSUE TITLE
Run list: distances should be run length, not distance from user

### ISSUE THREAD

**Issue by Gregliest** [AmericanWhitewater/aw-ios#126]
On the run list, the distance in miles in the bottom right of the cell should be the length of the run, not the distance from the user's current location. The user might not grant location permissions. If you don't have access to the run length, just remove that info for now and make a new issue to note that we should add that back in.

**Comment by duffek** [comment]
This is something that I added at the request of a few people I have testing. I'm happy to hide it, however there are two points to be made: 1) The distance is always valid. If they enter a zipcode we have their 'location' and I'm geo-coding that zip code to get their lat/long coordinates. 2) If they update their location then the distances are then re-calculated as well so the value stays up to date. But again, if we don't want the distanced listed we can just hide/remove it for later.

**Comment by duffek** [comment]
Hidden in TestFlight Build 19

**Comment by Gregliest** [comment]
Interesting, didn't realize it was a feature request. So the distance could be the distance from their home zip, not necessarily where they are currently? I think it's an interesting feature, to be able to sort/view by distance, but I think it will take a bit more UX thought to make it intuitive.
