### ISSUE TITLE
v20 map re-centers away from regions

### ISSUE THREAD

**Issue by AWKevin** [AmericanWhitewater/aw-ios#130]
I selected Montana as a region, and then went to the map tab. It opened on me here in NC which is not ideal but OK. I then zoom out and panned over to MT and the rivers were showing but then the app re-centers and zooms back to NC. This prevents use of the map to explore rivers other than those around the user at that time. 

Same issue remains that the auto-re-zoom is also tighter than a 100 mile distance so when I select distance I can't view the rivers on the map beyond a narrow zoom.

**Comment by duffek** [comment]
A few questions on this: 
**1) I selected Montana as a region, and then went to the map tab. It opened on me here in NC which is not ideal but OK.**
Was this on a first run? When the map first loads I have it loading your location while it loads the data. If a region is selected it should show the region? We could have it ignore the users location and show the annotations.

**2) I then zoom out and panned over to MT and the rivers were showing but then the app re-centers and zooms back to NC.**
Is this happening every time you move to the map? Or are you tapping on a button? I'm not seeing it force the user back to their location. Can you provide a list of steps to recreate this?

**Comment by AWKevin** [comment]
1) no not on a first run. I think if you select a region, and then click on map, you should see the region, not your location with no rivers. This is not the end of the world, except for #2 below makes it impossible to see the rivers. 

2) yes, every time I move the map by single finger sliding it just pans back to my location right away.

**Comment by AWKevin** [comment]
This remains a significant bug

**Comment by duffek** [comment]
Fixed in v21!
