### ISSUE TITLE
Need the color key to remain visible

### ISSUE THREAD

**Issue by AWKevin** [AmericanWhitewater/aw-ios#132]
The color key for what is running is currently only visible once, when I first opened the app for the first time. There needs to be a constant home for the color key on the app. Please look up the original solution for this.

**Comment by duffek** [comment]
I don't think I ever saw a legend on the original one and I'm not seeing one in the Zeplin designs. Maybe @Gregliest can point me in the right direction? In the current version there is an (i) button in the top left that will bring it back up to view. Also, I hate this design and view as it's ugly. It is justing something temporary. I have a better idea and I'll throw it together.

**Comment by AWKevin** [comment]
ooohhhhh, the little (i) button does this. I think this is OK for now - at some point be can make a more intuitive button with the 4 colors on it. We have bigger bugs to check off.

**Comment by duffek** [comment]
Ya for sure, I think this can look WAY better :)
