### ISSUE TITLE
Navigation to reaches? 

### ISSUE THREAD

**Issue by AWKevin** [AmericanWhitewater/aw-ios#133]
I know you used to have a way to exit to apple maps for navigation to a put in or takeout. Is this gone?

**Comment by duffek** [comment]
I thought this was something that we wanted removed. I saved the code and can put it back in. When tapping a putin or take out on the Reach's map icons? And maybe a Get Directions to put-in or take-out in the Details view?

**Comment by AWKevin** [comment]
Sorry for the confusion. Curious what Greg thinks / the old app had? 

I personally think that clicking on an icon on the regional map with lots of rivers should go to the river detail page, but clicking on the the river detail map icons for a take out or put in should go to apple maps.

**Comment by duffek** [comment]
I'm going to turn this back on and go with it, I can quickly remove if needed.
