### ISSUE TITLE
v22 access area icons (i) lead to map starting point rather than destination

### ISSUE THREAD

**Issue by AWKevin** [AmericanWhitewater/aw-ios#134]
I expect when I click on the access area on a river page map, especially the (i) icon, for the click to take me somewhere. It does nothing, which is confusing at a minimum. Ideally this would lead to navigation.

**Comment by duffek** [comment]
[Please verify this video is the response you are looking for.](https://www.dropbox.com/s/atbe9tgvypeu50t/awFix.mov?dl=0)

**Comment by AWKevin** [comment]
Please be sure that this is actually taking a person from their location to the access area, and not the other way around. It was hard to tell from the video.

**Comment by duffek** [comment]
So for Apple Maps I may need to tweak it to auto-fill the current location. Right now you have to select "Your Location" from within Apple Maps. I also think we can give the user a choice between Apple and Google maps if we want to. I'll test and see what can be tweaked.

**Comment by AWKevin** [comment]
The problem is, when I click on the access area it autofills in apple maps as the _starting point_. I don't want to start there, I want to go there. It should autofill as the destination. Then it is easy enough to click on "My Location" as the starting point.

**Comment by duffek** [comment]
Note, this was accidentally taken out when making my fixes. I'll update it before we submit.

**Comment by AWKevin** [comment]
This remains an issue on v22

**Comment by duffek** [comment]
Fixed in v24. Destination is shown correctly with user's location being default starting point.
