### ISSUE TITLE
v20 crashed 5-6 times, until it didn't. 

### ISSUE THREAD

**Issue by AWKevin** [AmericanWhitewater/aw-ios#135]
I was exploring the map and river pages and it was working. I switched to "runs" the app crashed. I tried to reopen it 5-6 times and every time I opened it, in about 1 second it crashed.

I quickly clicked on map before it could crash again and that worked, and I successfully switched back to runs. now it seems to be fine. Check out the crash log for around 2:55 today.

**Comment by duffek** [comment]
Just as an update, I've been tracking this down and there are a couple issues with data not being linked. I think I figured it out late last night but wanted to test today before I pushed anything.

**Comment by duffek** [comment]
Ok I think I have this one down. An issue with the crash reporting is preventing me from seeing it on Crashlytics. I've updated that so I am getting the correct files. We're going to have to test and try it out to verify it. *Possibly Fixed* v21.
