### ISSUE TITLE
v20 App Team needs updated

### ISSUE THREAD

**Issue by AWKevin** [AmericanWhitewater/aw-ios#136]
This page does not include David.

**Comment by duffek** [comment]
This brings up a good point, I did change this because the wording says "This app has been developed entirely with volunteer hours". Because of the grant and my involvement, how would you like this to read? I'm not picky at all and I'd prefer you and @Gregliest come up with some text for it.

**Comment by duffek** [comment]
I went ahead and added a little info. Please let me know if it needs to be approved. Build 23.
