### ISSUE TITLE
v21 Crash Report - Runnable rivers (Updated). 

### ISSUE THREAD

**Issue by AWKevin** [AmericanWhitewater/aw-ios#138]
I replicated this several times. 

on the distance based list of rivers, click on "runnable only", then click on a river, then click the back arrow. 

You'll see all rivers for a moment, and then it crashes. 

It also crashes if "only show runnable rivers" is selected and I go to the map, and then switch back to "runs" (the list)

When I reopen the app it shows all rivers listed, even though the only show runnable rivers is selected, then after after aa few seconds it shows only runnable rivers.

**Comment by duffek** [comment]
Update: I see whats going on with this. Trying to get it fixed now. Has to do with the filtering down to _only runnable_ rivers and updating the data.

**Comment by duffek** [comment]
Fixed in build 22. Build 23 with additional fixes also submitted.
