### ISSUE TITLE
Can’t go back to list after search

### ISSUE THREAD

**Issue by AWKevin** [AmericanWhitewater/aw-ios#145]
I searched for Deep Creek near me and it was the only result. I went to the river page, then clicked the back arrow. I ended up at the search results with no way to get back to the list. We need a back button. I deleted the search word and clicked done, which didn’t work. I clicked on runs - didn’t work. I clicked on map then runs and THAT worked. 
![BD8CD3FB-29FC-4588-9493-C80012015E9B](https://user-images.githubusercontent.com/7936679/71308848-5802c380-23cf-11ea-9443-fa33ea5e1922.png)

**Comment by duffek** [comment]
I’m seeing this too. I’ll fix and make another version to send to Apple to fix this. It’ll likely be approved right after the current version but we won’t release it to the public until this patch is fixed.

**Comment by duffek** [comment]
Ok I have this one fixed. It will be in version 1.3.1.
