### ISSUE TITLE
Delayed gage updating

### ISSUE THREAD

**Issue by AWKevin** [AmericanWhitewater/aw-ios#150]
Over the weekend I noticed that several gages said they were updated on the list and the river detail page but were not updating. The graphs were up to date, as was the AW page, but there was a significant lag on the list and river detail. This led me to think that rivers like big creek and south mills river were not running, when in fact they were upon closer inspection.

**Comment by AWKevin** [comment]
This happened again this morning. Runs List and river detail were showing day old data from my last session. It took 20 minutes or so and lots of checking to finally update. I think the graph was accurate - not sure.

**Comment by duffek** [comment]
Still investigating this.

**Comment by AWKevin** [comment]
Just checked and everything is up to date for the first time in recent weeks. I'll check again tomorrow. Looking good.

**Comment by duffek** [comment]
I believe our most recent update 1.3.2 fixed all of this. I'm going to keep an eye on it with all the most recent rain bumping things up too.
