### ISSUE TITLE
Auto Zoom out = poor UX

### ISSUE THREAD

**Issue by AWKevin** [AmericanWhitewater/aw-ios#151]
Go to a map of Oregon+washington, click on any river icon, close it, and the map auto zooms back out to the full 2 state view instead of staying in the same place. This makes searching multiple rivers in the same area frustrating.

**Comment by duffek** [comment]
Fixed this so it's not zooming back in. It auto zooms on the very first load, then keeps the zoom level consistent unless you press the "my location arrow" option.
