### ISSUE TITLE
Search UI/UX Issue not resolved

### ISSUE THREAD

**Issue by AWKevin** [AmericanWhitewater/aw-ios#154]
Now after a user searches they have to search for nothing and click done to get back to the main list. This is not intuitive. A  back button is.

**Comment by duffek** [comment]
@AWKevin clicking the X button clears and closes the search and resets it, right? 
Where do you see the back button going on the screen? I'm not opposed to this, just not sure where to place it in that smaller space.

**Comment by duffek** [comment]
I see the problem. Fixing in this next release as well.

**Comment by duffek** [comment]
Perm fix to this is now in place. Tested multiple times as well.
