### ISSUE TITLE
Can't add photo info fields

### ISSUE THREAD

**Issue by AWKevin** [AmericanWhitewater/aw-ios#156]
Adding a photo goes well until here, and then I get stuck. Clicking save photo does nothing. 
![BEDB4A08-9E46-487D-98D4-ECC3E38B5A29](https://user-images.githubusercontent.com/7936679/83173433-02051b00-a0e7-11ea-8585-92b0eb9ff678.png)

**Comment by AWKevin** [comment]
I can now add a photo, but can't add the required information: date, flow, author at a minimum.

**Comment by AWKevin** [comment]
There are no photo fields in the UI except for caption. We need the fields. See above.

**Comment by duffek** [comment]
@AWKevin can you send me a screenshot of the fields you want? I tried to visit the link but it's telling me I don't have permission to access it: 
![image](https://user-images.githubusercontent.com/6788776/94065760-888de880-fdb9-11ea-899a-1643f5f8d3a2.png)

**Comment by AWKevin** [comment]
<img width="1478" alt="Screen Shot 2020-09-24 at 9 42 32 AM" src="https://user-images.githubusercontent.com/7936679/94153795-35647600-fe4b-11ea-963c-6daa1da23fcb.png">
<img width="1457" alt="Screen Shot 2020-09-24 at 9 47 16 AM" src="https://user-images.githubusercontent.com/7936679/94153802-37c6d000-fe4b-11ea-918d-51773b4317ba.png">
<img width="796" alt="Screen Shot 2020-09-24 at 9 42 51 AM" src="https://user-images.githubusercontent.com/7936679/94153812-3ac1c080-fe4b-11ea-8053-0460d0e16e8e.png">

**Comment by AWKevin** [comment]
You should be able to see this page:
https://www.americanwhitewater.org/content/Report/new/

**Comment by AWKevin** [comment]
The fields we need, based on the list above are, with checks for the ones completed are:

- [ ] Country/State

- [ ] River Section

- [ ] Level observation

- [ ] Gage

- [ ] Numeric Reading

- [ ] Caption

- [ ] Author

- [ ] Subject

- [ ] Description

- [ ] Rapid Name

**Comment by AWKevin** [comment]
The form needs to additionally collect a numeric gage reading and subject at a minimum and perhaps rapid name.

As far as display goes, I think caption, date/time and numeric gage reading is important. No need to display the other stuff on the app.

**Comment by duffek** [comment]
@AWKevin what do you mean by *subject*?

**Comment by duffek** [comment]
fields are now added in
