### ISSUE TITLE
Can’t add alert

### ISSUE THREAD

**Issue by AWKevin** [AmericanWhitewater/aw-ios#157]
I tried to add an alert and it got stuck here, and then my screen stayed greyed out even when I backed out of this page: 

![29B479CC-34B1-450B-A925-83857E3738B2](https://user-images.githubusercontent.com/7936679/83173769-64f6b200-a0e7-11ea-90d6-695ba6a6ced2.png)

**Comment by duffek** [comment]
This was an issue with the beta server and how I was connecting. This has been fixed and will be in the next release.

**Comment by AWKevin** [comment]
No date appears on an alert added through the app.
