### ISSUE TITLE
Report your flows = no negative or decimal or inches options

### ISSUE THREAD

**Issue by AWKevin** [AmericanWhitewater/aw-ios#161]
There is no way to add a negative gage reading (-) or a decimal like 0.4 ft., and no way to add inches. These are essential, especially the - and decimal.

**Comment by duffek** [comment]
Switch to a number + punctuation/symbols keyboard. This allows for all of that.

**Comment by AWKevin** [comment]
Can you move bugs on the Project Board from To Do to, In Progress or Ready to Test, and then I can test, move them to done, and close them?

**Comment by duffek** [comment]
Ok, if I put them in Ready to Test, does that mean as soon as you get the build you know what to test, or do you want me to place them in "Ready to Test" once the TestFlight Build is ready?

**Comment by AWKevin** [comment]
Put them in In Progress until there is a version on TestFlight that I can test.
