### ISSUE TITLE
pulling limited photos

### ISSUE THREAD

**Issue by AWKevin** [AmericanWhitewater/aw-ios#164]
In looking at the Nolichucky and South Mills and others, it appears that the app is only pulling a subset of photos into the app. Is there a reason for this? Is there supposed to be a page button for moving to the next page? 

It is also not consistently showing captions etc which I assume is an issue with the API because the same is true on the production site.

**Comment by AWKevin** [comment]
@duffek do you need something from @ryangroth5 to fix this?

**Comment by duffek** [comment]
I had set this to only 10 photos when testing. I've updated this and as you scroll down it lazy loads (loads on demand) the images. This is why you will see them enter a loading view if the connection is slower. Great catch on testing!

**Comment by AWKevin** [comment]
This does not appear to have been fixed. 
I looked at Big Laurel. The photos on the app still appear oldest to newest, and only the oldest photos + one I added through the app appear. 18 total.

**Comment by duffek** [comment]
@AWKevin I didn't realize it was in reverse order. I'll fix that and I'll look into why it's only showing 18 photos. Can you verify that it's loading more photos on Chattooga IV?

**Comment by AWKevin** [comment]
I am seeing 10 photos on Section IV.

**Comment by AWKevin** [comment]
I kept pushing the arrow button next to the photos to see more and it doesn't work. You have to click the photos, which is counterintuitive but not the end of the world. 

On some pages I see a lot of photos, and others I do not, and they are out of order, and none have a date. 

This issue may be sufficiently remedied for release, and we can keep honing a bit.

**Comment by duffek** [comment]
Got this working.
