### ISSUE TITLE
Viewing reported flows

### ISSUE THREAD

**Issue by AWKevin** [AmericanWhitewater/aw-ios#165]
I went to "view and report your flows," and made a test entry for Big Laurel. My question is about viewing or consuming this information. What happens when I report a flow? I see it listed when I re-click "view and report your flows." Will I also see other people's reports? If so, the verbiage should be "view and report flows" since I'll not be viewing "your"/my flows, but everyone's. To me, flow reports might make more or additional sense to appear under the graph on "See Gauge Info" which could be renamed "Flow Info."  (regardless we should use the spelling Gage versus Gauge throughout." 

Also @ryangroth5 and @drewalth What happens to this information on the AW Website - is there a home for it and a similar UI for addition?

**Comment by duffek** [comment]
I've updated the language on this and I agree. I also think your second question to @ryangroth5 and @drewalth was discussed on a previous team call.
