### ISSUE TITLE
 No Alerts Appearing on some rivers

### ISSUE THREAD

**Issue by AWKevin** [AmericanWhitewater/aw-ios#171]
Check out the West Fork Tuckasegee. There are no Alerts list on the app, but there are some on the website that are less than 3 months old. I assume that rivers with no alerts also have no UI for adding alerts.

**Comment by duffek** [comment]
I'm investigating this. I didn't realize the "River Alerts" option wasn't showing up... that is very odd. Should be something simple.

**Comment by duffek** [comment]
Fixed. Had an old liked issue that was causing this option to hide. Fixed and tested on device and simulators.
