### ISSUE TITLE
Flow Report can't access camera

### ISSUE THREAD

**Issue by AWKevin** [AmericanWhitewater/aw-ios#172]
I tried to post a Flow Report but my camera screen is black when it opens. Using a stored photos works fine.

**Comment by duffek** [comment]
Did you reject the camera access property? I can add a check to take them to settings if they have. Also, does the camera work on the Gallery mode? If neither work, please check your camera app as well and let me know.

**Comment by AWKevin** [comment]
Same thing happens when adding a photo to a reach through the photo portal. I didn't reject anything as far as I know. 

I have an iphone X, it works fine for taking photos. Not sure what gallery mode is.

**Comment by duffek** [comment]
Ok, I got this working. If two pop-ups coming up to quickly it looks like it pushes the request to access the camera to the back. I've locked this down and if the request gets denied it let's the user know and takes them to fix it without entering into the camera.
