### ISSUE TITLE
1.3.5 See Gage Info shows "No Gages" when there are gages. 

### ISSUE THREAD

**Issue by AWKevin** [AmericanWhitewater/aw-ios#175]
See South Mills River, or any river. I'm not sure where you are pulling this information from, but it is not consistent with the website.

**Comment by AWKevin** [comment]
Also, more importantly, the See Gage info for South Mills goes to the Elk River flow tab, which is likely the source of the error.

**Comment by duffek** [comment]
now fixed in latest release
