### ISSUE TITLE
App is stuck on "Pull All Data?" Pop-up (v 1.3.6(1))

### ISSUE THREAD

**Issue by AWKevin** [AmericanWhitewater/aw-ios#177]
I switched to a distance sort and got a popup window that says "Pull all Data?." Pushing "Continue" to "Cancel" will not make it go away. Closing and reopening the app will not make it go away. 

In the background I can see it loaded all rivers in the US (or at least 3 states) alphabetically, rather than just 80 miles.

**Comment by duffek** [comment]
I finally found this issue. It was a display error where the popup was displayed twice on top of itself. I've fixed the issue and put a fix in place for all future popups so it wont lock the user out.
