### ISSUE TITLE
Newly installed app crashed (v 1.3.6(1))

### ISSUE THREAD

**Issue by AWKevin** [AmericanWhitewater/aw-ios#179]
I deleted and reinstalled the app through TestFlight and it opened, issued a pull all data popup, and then crashed. I re-opened the app and it works (but not distance sorting)

**Comment by duffek** [comment]
I'm not sure what happened with tis. I think it was an issue with some of the older test code that was preventing the filtering by location. BUT I updated and fixed crashlytics so I'll get notified on future crashes and more debug info on them.
