### ISSUE TITLE
Can't add photos - no camera access. (V 1.3.6(1))

### ISSUE THREAD

**Issue by AWKevin** [AmericanWhitewater/aw-ios#181]
When I try to add a photo I get a pop-up
![IMG_3355](https://user-images.githubusercontent.com/7936679/97721808-4b93d080-1aa0-11eb-95f3-7e9db6b331dd.PNG)
then the options do not include camera
![IMG_3356](https://user-images.githubusercontent.com/7936679/97721832-53ec0b80-1aa0-11eb-8b3b-e094f1d6d5ac.PNG)

**Comment by duffek** [comment]
Photos are all fixed. It was blocking the permission from being asked for in some instances. This has been updated to match apple's guidelines and requirements going forward as well.
