### ISSUE TITLE
Failed Login results in Broken Flow

### ISSUE THREAD

**Issue by ingalls** [AmericanWhitewater/aw-ios#182]
### Context

I attempted to login via the new "Sign in with your AW Account" splash upon initial app load. Upon attempting to login, I must have mistyped my password/email, resulting in a failed login attempt.

Subsequent attempts are now impossible, even after closing the app and result in safari opening to a page containing the following:

```json
{
"error": "invalid client",
"error_description": "Client authentication failed",
"message": "Client authentication failed"
}
```

### Device Details

```
AW App: v1.3.4
IOS: 14.0.1
```

### Desired Outcomes

- Don't show a raw JSON error message to the user
- Show an error page allowing the user to re-attempt login

I'm afraid I'm not a mobile developer and my knowledge of swift is non-existant, but happy to help in any way I can. Absolutely love the app! 

cc/ @Gregliest @abkfenris @AWKevin

**Comment by Gregliest** [comment]
@duffek

**Comment by duffek** [comment]
I got this fixed, it had some issues with the logout and the sever aligning. This is all working and tested multiple times. I hope this will be confirmed by the testers. Thanks!
