### ISSUE TITLE
Flow Report level should not be required

### ISSUE THREAD

**Issue by AWKevin** [AmericanWhitewater/aw-ios#186]
Not all rivers have gages, and photos are the relevant thing to post. Think Pigeon Dries. I tried to add a photo without adding a numeric flow and got this blocker. Please disable this constraint to allow photos without a numeric flow. This is my opinion, but perhaps there is a reason my view doesn't make sense? 
![IMG_3548](https://user-images.githubusercontent.com/7936679/99669116-9c15a280-2a3c-11eb-892a-1cea1892a862.PNG)

**Comment by AWKevin** [comment]
Not getting this error, but flow report not working.

**Comment by duffek** [comment]
Is this issue still working on this

**Comment by duffek** [comment]
This is fixed.

**Comment by AWKevin** [comment]
I tested this and did not see the change reflected. Moving back to in progress.

**Comment by duffek** [comment]
hmm looking at it now!

**Comment by duffek** [comment]
must have undid my fix somehow... fixed again! :)
