### ISSUE TITLE
Posting photos = "An Error Occured"

### ISSUE THREAD

**Issue by AWKevin** [AmericanWhitewater/aw-ios#188]
I tried to post a photo and got a popup saying "An Error Occurred [internal server error]" when I clicked "Save Photo."

**Comment by AWKevin** [comment]
This is still occurring with 1.3.8(2)

**Comment by AWKevin** [comment]
I can now post a photo. Version 1.3.8(5)

TBD I guess if this will show up on the AW website right? Should it show up on Beta? I posted a new photo on South Mills River (Test Caption, Test Description). 

Can we turn on the other fields now?

**Comment by duffek** [comment]
Turning on the other fields. At one time there was a server issue where it wasn't handling my uploads. I'll get with @ryangroth5 on this to see if this is still an issue. I'll create a new issue for the photo fields.
