### ISSUE TITLE
Only rivers in my state show up (Distance sort)

### ISSUE THREAD

**Issue by AWKevin** [AmericanWhitewater/aw-ios#189]
I X-out the state sort so it shows nothing and select distance sort, and cant see any rivers that are not in NC. repeated numerous times. Even search will not see rivers out of the state.

**Comment by duffek** [comment]
Fixed this issue. It was an issue with permissions for gaining access to location. If it wasn't never requested (which is possible with the standard flow of the app) then it wouldn't allow it to work but didn't say anything. Now it requests location access and works correctly as before. To test this, deleting the app and starting again will help.

**Comment by AWKevin** [comment]
Nice, this seems to be working well now.
