### ISSUE TITLE
Only "Day" works on flow tab 

### ISSUE THREAD

**Issue by AWKevin** [AmericanWhitewater/aw-ios#190]
week, month, year does not work. the buttons are not live.

**Comment by AWKevin** [comment]
I'd be fine if we only had week and day. Even only having week in a pinch would be OK.

**Comment by duffek** [comment]
I can switch it to week easily, I'll do that now and push out an update. I have a fix for the others but want to get the location issue fixed as well.

**Comment by AWKevin** [comment]
This does not work on the new version.

**Comment by duffek** [comment]
What river is this not working for you on?

**Comment by AWKevin** [comment]
It works now!
