### ISSUE TITLE
flow tab graph y axis must start at 0

### ISSUE THREAD

**Issue by AWKevin** [AmericanWhitewater/aw-ios#191]
The graph currently starts at the lowest value for the day. This is non-standard and confusing, essentially zooming in on the fluctuation in the timeframe rather than showing the standard shape of the hydrograph.

**Comment by AWKevin** [comment]
Much better. This works on Version 1.3.8(5)

**Comment by duffek** [comment]
Great, I have a bunch of fixes still to come!
