### ISSUE TITLE
New member can't sign into app

### ISSUE THREAD

**Issue by AWKevin** [AmericanWhitewater/aw-ios#194]
On Mon, Jan 25, 2021 at 10:58 AM dockayak <dockayak@gmail.com> wrote:

Greetings

I recently renewed my AW membership. 

I’m having difficulty with the app on my iOS. It won’t allow me to sign in with my password sent from AW. How can I fix that issue or who can assist?

Thanks

Geoff

**Comment by duffek** [comment]
Geoff,

We have a new version that is pending approval from Apple. As soon as it's ready it'll be ready and working for you. We have an issue where some accounts aren't connecting that has been resolved and will hopefully be released in the next day or two.

**Comment by duffek** [comment]
The new version of the app is released! Please try and sign in and let me know if you continue to have issues with your account! 

Note: just seeing this was your post @AWKevin I'm emailing the guy right now.
