### ISSUE TITLE
Photo Upload compressing file size

### ISSUE THREAD

**Issue by AWKevin** [AmericanWhitewater/aw-ios#195]
I uploaded a 652 KB photo to Section 1 of the Chattooga through the app. It appeared on the website, but even the "full resolution" version is 191 KB. We need to upload full resolution photos without compression. Any idea why this is happening? 

See most recent photo at https://www.americanwhitewater.org/content/River/view/river-detail/1049/gallery

**Comment by duffek** [comment]
I'm checking to see if the app is causing this. I tend to default to a medium resolution when doing file upload and I'm sure I copied and pasted code from another app I developed. If this isn't it, then it might be a server issue. I'll find out and share this info with the team if needed...

**Comment by AWKevin** [comment]
Ryan has made some changes on the backend, some of which are live, but the app is still compressing photos to 136kb. The SPA is not doing this, so I assume the problem is on the iOS App.

**Comment by AWKevin** [comment]
Have you made any progress on this one? Got questions for the group?

**Comment by AWKevin** [comment]
FYI - the site does not accept HEIC photos right now. So maybe this is a related issue?

**Comment by AWKevin** [comment]
This remains among the most vexing issue with the App. We don't want junk (low res) photos and we do want good ones, so having the app compressing photos is a hit to our work. This one should be a priority.

**Comment by yeahphil** [comment]
I was able to repro and took a look at this.

It appears the iOS standard image picker controller downsamples the edited image if you allow editing (like cropping) which the app currently does. I didn't know that. Doesn't seem well documented anywhere.

Anyway, I manually applied the crop to the image and verified that after this PR is applied the app sends a full res JPEG to the server. It goes up via the GraphQL API.

But now when I try doing an upload now, it's still coming out pretty small -- like 800x600 for my test image (which was like 4000x3000 to start). Over to the server side? Looks like whatever else is resizing must be happening there.

**Comment by Gregliest** [comment]
@yeahphil Where did you upload that photo to? It's possible is a proper size on the server and it's just handing the app back a smaller image.

**Comment by yeahphil** [comment]
Argh, I deleted it when I was done. I’ll have to upload another copy tomorrow when I’m back at my desk.

That said, I was checking my upload on the website and couldn’t get a high-res image there.

**Comment by AWKevin** [comment]
There should be Filesize field depicted on the  photos' page + a specific link/button for Full Resolution version. If however you just click and save the photo on that Preview page it should be 800 wide. Apologies if that is all obvious. 

<img width="1367" alt="Screen Shot 2021-07-20 at 7 54 50 AM" src="https://user-images.githubusercontent.com/7936679/126319726-0b984ffc-0631-45ad-8a72-1a79ac1e489c.png">

When we know for sure I can put the website crew on the quest for figuring out what the server side is doing.

**Comment by yeahphil** [comment]
@AWKevin ah, I totally missed that.

Looks like this is working! Just uploaded another copy of a test pic: https://www.americanwhitewater.org/content/River/view/river-detail/3066/gallery/2rpzEWkZ4Ar4hpQc7fvPG

**Comment by AWKevin** [comment]
Awesome!

**Comment by AWKevin** [comment]
Tested and working great.
