### ISSUE TITLE
Caption in a Flow Report should not be mandatory

### ISSUE THREAD

**Issue by AWKevin** [AmericanWhitewater/aw-ios#198]
I submitted a flow report and the mandatory Caption left me scratching my head (A photo, the level, and the runnability kinda says it all). Lets make this non-mandatory if that is OK. If that a is complicated don't worry about it.

**Comment by AWKevin** [comment]
This works. The Caption now defaults "Trip Picture." Nice.

**Comment by AWKevin** [comment]
This is not currently fixed on the Production app. Should it be?

**Comment by Gregliest** [comment]
Yeah it should be but I didn't get a chance to test. I must've misunderstood where the issue is.

**Comment by AWKevin** [comment]
This is not fixed. I still get the "Caption Required" pop up

**Comment by AWKevin** [comment]
I tried to add a flow report with a photo and no caption to the Swannanoa River here in NC. The UI worked well and it appeared to post, but the Report does not appear on the app. Is this an artifact of the TestFlight environment or a issue with the bug fix?

**Comment by Gregliest** [comment]
@AWKevin We were experiencing a long delay posting these reports before they came back to the app. Are you seeing it now? Also, if the caption is fixed, would you mind opening a new issue for any new bugs with the flow report?
