### ISSUE TITLE
App not pulling rivers near me in NC - only near me in other states

### ISSUE THREAD

**Issue by AWKevin** [AmericanWhitewater/aw-ios#200]
I returned from TN to NC, and switched to Distance mode and reset my location. It is showing the runs closest to me, but NOT in NC. Only SC and TN. 

I then selected NC out or regions and the NC rivers appeared. Then I closed that and selected Distance again and now NC rivers are loading correctly by distance.

**Comment by Gregliest** [comment]
Do you have repro steps for this?

**Comment by AWKevin** [comment]
I'll have to travel to try to reproduce this. Stay tuned...

**Comment by Gregliest** [comment]
I think this should be fixed by https://github.com/AmericanWhitewater/aw-ios/pull/243. I'm going to close for now, we can reopen if necessary.
