### ISSUE TITLE
Connection Error message happening frequently

### ISSUE THREAD

**Issue by AWKevin** [AmericanWhitewater/aw-ios#201]
When using the app I frequently get this message, though I am unsure of the exact pattern of use that triggers it. 

![IMG_4425](https://user-images.githubusercontent.com/7936679/113168234-7c745f00-9212-11eb-8262-789e62cb8809.PNG)

**Comment by AWKevin** [comment]
I've not seen this lately, perhaps you fixed it?

**Comment by AWKevin** [comment]
I saw this error a couple time recently.

**Comment by AWKevin** [comment]
I just got this error message again.

**Comment by Gregliest** [comment]
These should be toasts instead of dialogs that interrupt the user.

**Comment by AWKevin** [comment]
I am not getting this message on TestFlight. Seems to be remedied.

**Comment by AWKevin** [comment]
I am not getting this error on the Production app anymore.
