### ISSUE TITLE
App is Not Loading Data

### ISSUE THREAD

**Issue by AWKevin** [AmericanWhitewater/aw-ios#203]
I am not sure when this started, but as of Friday the App will not load any data. It says "Loading River Data..." with a spinning wheel.

**Comment by Gregliest** [comment]
Is this still happening?

**Comment by AWKevin** [comment]
No. It is not. But - I had to delete and reinstall the app to stop it. I am unsure what caused this or how many users it affected. David looked into it and didn't find anything. I'll close this ticket and keep an eye out for recurrence.
