### ISSUE TITLE
Loading river data screen shows when there is no data

### ISSUE THREAD

**Issue by Gregliest** [AmericanWhitewater/aw-ios#206]
Reproduction: Set filters such that there are no rivers (distance filter < 5 miles should do it, depending on where you are). 

See: "Loading River Data" with the spinner.

**Comment by Gregliest** [comment]
Related to https://github.com/AmericanWhitewater/aw-ios/issues/208

**Comment by yeahphil** [comment]
@AWKevin @Gregliest see what you think of this (I guess we maybe need to merge and testflight for that). I'm confident it makes things better, but I still think it's confusing.

Maybe what's needed now is to change the empty cell state? It's a little confusing about why there aren't any results, maybe it should show the filters, something like: 

---
No rivers available
Matching (Distance: 100mi from xxx) (Search term: gnarnia)

(Change Filters)
---

**Comment by Gregliest** [comment]
Yeah I think that's a great idea for a UX change.
