### ISSUE TITLE
Distance slider is jumps back to 100 miles

### ISSUE THREAD

**Issue by Gregliest** [AmericanWhitewater/aw-ios#207]
If you try to scroll to the left end of the distance slider and go off the end, it jumps back to 100 miles instead of staying at 0.

**Comment by yeahphil** [comment]
Can you still repro this? I think it got fixed somewhere along the way.

Also https://github.com/AmericanWhitewater/aw-ios/tree/filters has some changes to behavior here -- distance label updates as you drag

**Comment by Gregliest** [comment]
Oh cool, yeah looks like this got fixed. Wonder what did it.
