### ISSUE TITLE
Update UI around loading flows

### ISSUE THREAD

**Issue by AWKevin** [AmericanWhitewater/aw-ios#208]
The river list flow and river page flow on the app took around 4-5 minutes to update, but there was no indication (that I noticed) that they were not updated. graph page was correct. This is not right. Especially on the river page the flows should be updated upon opening the page, even if the list must take a while to update.

**Comment by Gregliest** [comment]
Was the last updated at date at the top of the list view correct (ie did it show that the last update was stale)?

**Comment by AWKevin** [comment]
No, I believe the Last updated timestamp is always the moment you open the app, regardless of the data. 

One UI thing is that when you open on the list of flows you see the skinny wheel, but when you scroll down to look at flows that disappears above the screen, so it is out of mind. And the Updated timestamp is now, so I clicked on a river page and the flow was old without indication. I just did it again and it took maybe a minute to update, but by that time I would usually have checked the flow and moved on.

**Comment by AWKevin** [comment]
I checked in on this again. Flows update in a reasonable timeframe. The problem is IMO purely in how we tell people that flows are updating (and hence not updated). I recommend:

1. Have the "Last Updated: July 20, 2:11pm" refresh when the spinning wheel stops rather than when you open the app. 
2. Have the spinning wheel remain visible at the top of the list along with the "Last Updated..." message while scrolling, rather than scrolling out of sight. 
3. Add a spinning wheel to the river page where it is prominent along with the flow reading.

**Comment by Gregliest** [comment]
Alright, we've done 1. 

For 2. @yeahphil do you know how to keep the spinner sticky at the top?

3. is complex, and we probably won't end up doing that. That would require a lot more control over data loading, and knowledge of the state of api requests. The app really needs to be designed from the ground up to support that kind of feature.

**Comment by AWKevin** [comment]
Number 1 is a good safety fix - Nice!

Thumbs up on skipping Number 3.

**Comment by Gregliest** [comment]
Going to close this for now, sounds like number 2 isn't possible with the built in iOS table view. We hopefully fixed the update time with https://github.com/AmericanWhitewater/aw-ios/pull/261.

**Comment by AWKevin** [comment]
Looks good. The "Last Updated" timestamp does not update until the data updates.
