### ISSUE TITLE
Only support iOS 13 and up

### ISSUE THREAD

**Issue by yeahphil** [AmericanWhitewater/aw-ios#215]
**Here's the pitch:**

- The app currently supports iOS 11 and up
- >95% of users are currently on iOS 13+ according to Firebase. 0.6% are iOS 12.5.4 and 3.6% 'other' (only some of which will be older than iOS 13)
<img width="517" alt="image" src="https://user-images.githubusercontent.com/66321/126374802-2094bc3c-9418-42c0-95b6-bcec82b4f10e.png">
- Dropping older releases will prevent users on iOS 11/12 from getting updates, but they'll be able to continue using the last version to support their OS.
- Users that get dropped can still use the website, so they won't be losing access to information

**The payoff:**

iOS 13 was a watershed release, notable for Combine (a system library for managing streams of value over time), SwiftUI (new UI framework), and SF Symbols (standard system icon library), all of which might be handy in a few places in the app. There's also just a lot of little new stuff that would be nice to use without having to provide backwards compatible workarounds for a small number of users on old OS versions.

**Comment by Gregliest** [comment]
That sounds great to me. I propose that we cut this release and make that the last supported version for the older versions. Then we can drop 11 and 12 for the next one. Thoughts?

**Comment by yeahphil** [comment]
I think that's a good approach!

**Comment by Gregliest** [comment]
https://github.com/AmericanWhitewater/aw-ios/pull/247
