### ISSUE TITLE
Map won't stay zoomed in on a river

### ISSUE THREAD

**Issue by AWKevin** [AmericanWhitewater/aw-ios#226]
On TestFlight: I chose Filter By Region --> Montana. I select a specific river and to the the river page, and click on Map at the top. map opens on almost the whole Country, I assume to show me (in NC) and the river (in MT). When I try to zoom in on the river, if it lets me at all, it pretty quickly zooms back out. This makes it impossible to explore a river's map unless maybe you are on that river when you are doing it. 

Fix should be to have river pages zoom to the map of the river, regardless of the location of the phone/viewer. 

![IMG_2DACA1FCB003-1](https://user-images.githubusercontent.com/7936679/126690334-4b98e60f-4685-4e6c-b81a-387f8e53e3c3.jpeg)

**Comment by Gregliest** [comment]
Hmm, I'm not able to repro this bug. However, we probably shouldn't be showing the user's location by default anyway so I'll change that.

**Comment by AWKevin** [comment]
Weird. Just to confirm it I selected Tennessee, and pulled up the Big South Fork. As expected the map was framed with My location on the east end of it and the BSF on the west side of it. I zoomed in on the BSF and it returned to the wide view automatically after a few moments.

**Comment by AWKevin** [comment]
Confirmed this is fixed. Excellent.
