### ISSUE TITLE
Map should not zoom every time

### ISSUE THREAD

**Issue by Gregliest** [AmericanWhitewater/aw-ios#231]
On the Run Map page, if you click a marker to see a Reach Detail page, and then go back, the map will zoom back out to all points. This is annoying if you are trying to explore reaches in a particular area. 

Desired behavior:
- Only auto zoom if the filter changes.

**Comment by yeahphil** [comment]
Fixed this in the referenced commit... but I lost zooming animations in the process because of timing changes (the animation is happening as the filter controller dismisses).

Is that important?

**Comment by Gregliest** [comment]
I think that's an improvement, so yeah, should be fine. We can figure out how to add it back if we want later.
