### ISSUE TITLE
Map view filters with runnable filter, but it's only visible/settable from the runs list view

### ISSUE THREAD

**Issue by yeahphil** [AmericanWhitewater/aw-ios#238]
The map view now filters with the runnableFilter ("Only show runnable results"), which isn't settable from the map view.

I think it's useful but you should be able to tell it's happening. Thoughts?

**Comment by yeahphil** [comment]
Oops, I should say this is the case in the filters branch, not merged yet. See https://github.com/AmericanWhitewater/aw-ios/blob/0944ef9a40a05296cdf9c4dd9834ae3a0464a184/American%20Whitewater/ViewControllers/Map/MapViewController.swift#L93

**Comment by Gregliest** [comment]
Hmm, interesting. Not ideal, but not the worst too. Can't think of a clean way to add that option or an indicator to the map, seems like it would just clutter the screen. And it is nice to be able to only see runnable on the map, since the pins can be hard to click. Yeah let's go with this for now.
