### ISSUE TITLE
Filter by Region: check mark

### ISSUE THREAD

**Issue by Gregliest** [AmericanWhitewater/aw-ios#242]
On the Region Filter page, if you choose a region, it shows up in the top cell and a check mark shows up next to it. If you hit the "x" button to clear it, the check mark remains. The check mark should go away (and generally the check marks and the list at the top should be in sync).

![IMG_1A73CAA5C4AB-1](https://user-images.githubusercontent.com/4493287/128729501-8d9f59e6-6e6e-4ef5-8d43-81b318e71814.jpeg)

**Comment by yeahphil** [comment]
I fixed this in the filters branch! I guess we should probably review & merge that.

**Comment by Gregliest** [comment]
Fixed by https://github.com/AmericanWhitewater/aw-ios/pull/243

**Comment by AWKevin** [comment]
The whole process of flipping between Distance and region is much improved.
