### ISSUE TITLE
Change Filter active filter type to an enum

### ISSUE THREAD

**Issue by yeahphil** [AmericanWhitewater/aw-ios#244]
Filter kind is a toggle -- you can either filter by one or the other, not both. Currently this state is stored in two Bools, `showDistanceFilter` and `showRegionFilter`, which are meant to be kept in sync. That's error prone and it's not clear they can't both be true/false. This should be an enum, something like:

```
    enum ActiveType {
        case distance
        case region
    }
    
    var activeType: ActiveType
```

**Comment by Gregliest** [comment]
Fixed by https://github.com/AmericanWhitewater/aw-ios/pull/250
