### ISSUE TITLE
Map icons flashing and stuck

### ISSUE THREAD

**Issue by AWKevin** [AmericanWhitewater/aw-ios#262]
I was on a run page (Nolichucky) and then clicked map at the bottom to see all the runs in the area. the icons for all the runs pulse/flash in roughly 1-second increments and clicking one will open the river name icon for 1-second and then it closes. 

Replicated: Go to a run, go to the map for that run (top of page map option), then click on Map at the bottom of the page.

**Comment by Gregliest** [comment]
This is related to the location distance updates. Not sure why it's updating the map though.

**Comment by yeahphil** [comment]
@Gregliest I took a quick look at this, looks like `DefaultsManager.shared.lastDistanceCoordinate` doesn't get updated when reach distances get set, so distances update every time the map's user location updates.

**Comment by Gregliest** [comment]
@yeahphil Yes, see https://github.com/AmericanWhitewater/aw-ios/pull/266
