### ISSUE TITLE
When error is thrown, refresh spinner does not disappear

### ISSUE THREAD

**Issue by Gregliest** [AmericanWhitewater/aw-ios#82]
This happens on the Favorites and News pages at least. Relevant code lines are [here for News](https://github.com/AmericanWhitewater/aw-ios/blob/f805983acdef19ac2d0e416ee09f521c22453a69/aw/Helpers/AWArticleAPIHelper.swift#L14) and [here for Favorites](https://github.com/AmericanWhitewater/aw-ios/blob/f805983acdef19ac2d0e416ee09f521c22453a69/aw/Helpers/AWApiHelper.swift#L41).

**Comment by duffek** [comment]
Fixed - TestFlight Build 1.3 (3) - Public release soon!
