### ISSUE TITLE
AW IOS data refresh and initialization broken since 6/26/2019

### ISSUE THREAD

**Issue by headhertz** [AmericanWhitewater/aw-ios#83]
I think I first noted that data would not refresh in the app on 6/26/19.  At the time http://www.americanwhitewater.org was also serving an error page.  The website error was fixed later that day but the IOS app still will not refresh data.  I also tried removing/reinstalling and now it also will not initialize.  A fresh initialization on another IOS device also fails.

**Comment by riversandcreeks** [comment]
Thanks @headhertz for flagging; @AWBethany noted similar feedback from members emailing her.

**Comment by Gregliest** [comment]
I'll be able to have a look at this tomorrow.

**Comment by Gregliest** [comment]
@mattanger @ryangroth5 Found one error, looks like this endpoint, https://www.americanwhitewater.org/content/River/list/list/4003:1154/.json, is returning numbers instead of strings for the following fields: `plat`, `plon`, `tlat`, `tlon`.

I think there's another error as well, I'll keep poking around.

**Comment by headhertz** [comment]
Any progress on this?  I am still unable to initialize the app.

**Comment by duffek** [comment]
Hey guys, thanks for your patience and this is fixed in a coming update. We've also added a little more error handling to prevent issues like this in the future. As always, we hope you'll continue to test and let us know what you think! I'll comment and close this after we finish testing asap!

**Comment by AWKevin** [comment]
The new version of the app is live that remedies this issue.
