### ISSUE TITLE
Location map only shows my state

### ISSUE THREAD

**Issue by AWKevin** [AmericanWhitewater/aw-ios#84]
@duffek the map feature only shows runs in my state, rather than a radius around me regardless of state borders. Can we go back to a radius? 

![Image-1-2](https://user-images.githubusercontent.com/7936679/66086033-e12cfb80-e540-11e9-82b3-2193b8a2818b.jpg)

**Comment by duffek** [comment]
Absolutely! See Issue Issue #89 
Duplicate of #89
