### ISSUE TITLE
River Details page description largely hidden 

### ISSUE THREAD

**Issue by AWKevin** [AmericanWhitewater/aw-ios#86]
There is no way to actually read the text of the description that I can figure out. Only the title and a couple lines are shown. 

![Image-1-4](https://user-images.githubusercontent.com/7936679/66086484-34ec1480-e542-11e9-9ef9-2f90138d1ea9.jpg)

**Comment by duffek** [comment]
Fixed - TestFlight Build 1.3 (3)
