### ISSUE TITLE
Map Icons go to AppleMaps rather than River Detail

### ISSUE THREAD

**Issue by AWKevin** [AmericanWhitewater/aw-ios#88]
Clicking on the (i) icon after clicking on any river icon on the Map takes me to apple maps rather than the river detail page in the app. This does not make sense to me. I want to learn more about rivers through the map just like through the list, not leave the app for directions. I suggest that the (i) should go to the river detail page, and from there you should be able to bounce to apple maps.

**Comment by duffek** [comment]
Fixed - See TestFlight Version 1.3 (3) 

(working on this for the RiverDetails map view for rapid explanations and an option to get directions for the put-in or take-out - We'll likely have this in TestFlight Build (4))
