### ISSUE TITLE
Region and Distance often conflict = confusing

### ISSUE THREAD

**Issue by AWKevin** [AmericanWhitewater/aw-ios#92]
I picked Montana as a region and that did not jive with my Distance selection so I got a No Rivers Available page. I think region and distance need to be an "either-or" option rather than a "both-and" option. In other words, if a user picks a Region then their Distance pick is cleared, and if a user picks a distance their region pick is cleared. Class on the other hand should remain an option that filters along with either distance or region.

**Comment by RacIVRnr** [comment]
Personally, I'm not sure that this should be an either/or situation. I would rather see it as a specific user-selected option.

As an example: I live relatively near the border between WI and IL. However, for various reasons, I very rarely travel into IL for boating. Therefore, I like having the OPTION of being able to say "show me all rivers within xxx miles (regardless of which state they are in)" OR "show me all rivers within xxx miles JUST IN WISCONSIN".

Is this a big deal? No, not really. I can easily just ignore those runs. However, it would be nice to let users decide which way they want the app to work between these two options.

**Comment by duffek** [comment]
@RacIVRnr this is a great point. I'm going to have to dig into playing with this. I'm going to initially change it to simplify it for this next stable version but we can test this some more with your help. Thanks for diving into it and providing a good example. I've been up to Bear Paw (not to long after the tornado!) and on the Menominee as well as other runs. I was an Indiana boater for a long time!

**Comment by AWKevin** [comment]
If I click on regions, Montana, done: I see rivers on the list that are proximal to me here in NC because I have a distance selected (100 miles) and I see no rivers from MT. When I selected a region I expected to see that region and have it negate my distance pick. If I turn off the distance I see only MT. I found this confusing. I am not sure if this is wrong, or unintentional, but it was confusing to me to have to go back and turn of a prior choice to see my new choice. I guess @RacIVRnr and I differ on this, so I am cool with either approach. 

I can now turn off a region: Great

**Comment by duffek** [comment]
After a survey we've decided to go with the OR option. This can be easily changed based on future feedback. TestFlight Build 11

**Comment by Gregliest** [comment]
Yes, how @AWKevin originally described the "either-or" option is how the Android app works, and how this was designed to work. Selecting a region should clear distance and vice versa. There should be a toast or other notification when that happens. Combining these would be nice as @RacIVRnr pointed out, but Rachel and I couldn't figure out an elegant way to communicate what was happening from a UX perspective. As it is, I think it could still be clearer what filters are being applied on the various screens.
