### ISSUE TITLE
App should default to the "Runs" tab

### ISSUE THREAD

**Issue by Gregliest** [AmericanWhitewater/aw-ios#94]
On a fresh install, I entered my zip code and the app defaulted to the "News" tab. It should go directly to the "Runs" tab.

**Comment by duffek** [comment]
@Gregliest @AWKevin is this what we want? If so shouldn't we just move the Runs tab as the first option in the list and then the news feed to be the 3rd? [ Runs | Favs | News | More ]?

**Comment by Gregliest** [comment]
Works for me to reorder. Also, keep in mind that the app should default to Favs if favorites are present.

**Comment by duffek** [comment]
Fixed - TestFlight Build 5
