### ISSUE TITLE
"Last Update" is the wrong font size and color

### ISSUE THREAD

**Issue by Gregliest** [AmericanWhitewater/aw-ios#95]
![unnamed](https://user-images.githubusercontent.com/4493287/66524913-a4b15080-eaa8-11e9-803f-feed1de70e48.png)

The font should be 12pt, centered, font gray color. Also check that the background is the correct gray color, and that the spacing around the text is correct.

**Comment by duffek** [comment]
Fixed in TestFlight Build 5
