### ISSUE TITLE
Can't go back to "details" from "map"

### ISSUE THREAD

**Issue by Gregliest** [AmericanWhitewater/aw-ios#96]
On a run details page, if I click "map" it brings me to the map. But, clicking on the details tab to go back to details does nothing. 

The tab seems to be wonky on the details page too. If I click back and forth a couple of times, sometimes, on the details page, clicking on "map" does nothing, but clicking on "details" will bring me to the map.

**Comment by duffek** [comment]
Fixed in TestFlight Build 4
